### ISSUE TITLE
Optimize dark mode and light mode in the TextForm Component

### ISSUE THREAD

**Issue by Suyash99** [Suyash99/Text-Utils-React-#1]
Clicking on the "Enable Dark Mode" Button enables the dark mode and "Enable Light Mode" enables the light mode. Optimize the component  TextFrom section dark mode and light mode feature

**Comment by Suyash99** [comment]
@Vishal1297

**Comment by Vishal1297** [comment]
Let me first read your code after that i will start on this.

@Suyash99

**Comment by Suyash99** [comment]
@Vishal1297 Closing This since this is resolved and live on master branch
